name: newtify
version: 1.2.3
description: >-
  Have you been turned into a newt?  Would you like to be?
  This package can help. It has all of the
  newt-transmogrification functionality you have been looking
  for.
author: riseremi
homepage: https://homeproto.netlify.com
documentation: https://homeproto.netlify.com
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
dev_dependencies:
  build_runner: '>=0.8.10 <2.0.0'
  build_web_compilers: '>=0.3.6 <0.5.0'
